//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapitalTimePieces.Views.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapitalTimePieces.Views.Email.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Sellers Information&lt;/h2&gt;
        ///&lt;p&gt;Name: [NAME]&lt;/p&gt;
        ///&lt;p&gt;Email: [EMAIL]&lt;/p&gt;
        ///&lt;p&gt;Phone: [PHONE]&lt;/p&gt;
        ///
        ///&lt;h2&gt;Watch Information&lt;/h2&gt;
        ///&lt;p&gt;Brand: [BRAND]&lt;/p&gt;
        ///&lt;p&gt;Model: [MODEL]&lt;/p&gt;
        ///&lt;p&gt;Dial Description: [DIALDESCRIPTION]&lt;/p&gt;
        ///&lt;p&gt;Estimated Value: [ESTIMATEDVALUE]&lt;/p&gt;
        ///Additional Comments: &lt;br/&gt;
        ///[COMMENTS]&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string SellWatchTemplate {
            get {
                return ResourceManager.GetString("SellWatchTemplate", resourceCulture);
            }
        }
    }
}
